# Generated by Django 4.2.1 on 2023-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADM', 'Admin User'), ('REG', 'Registered User'), ('UNR', 'Unregistered User')], max_length=3, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='telegram ID'),
        ),
    ]
