# Generated by Django 4.2.1 on 2023-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO code')),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='balance')),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='goal')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='balance')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='FundBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=1, verbose_name='budget period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='budget amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='renew')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer')], max_length=2, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='transferred amount')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='UserBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=1, verbose_name='budget period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='budget amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='renew')),
            ],
        ),
    ]
