# Generated by Django 4.2.1 on 2023-08-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbudget',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.fund'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='fundbudget',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.fund'),
        ),
        migrations.AddField(
            model_name='fund',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='userbudget',
            unique_together={('user_profile', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='fundbudget',
            unique_together={('fund', 'period')},
        ),
    ]
